spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/flixfinder}
    username: flixuser
    password: flixpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
openai:
  apiKey: dummy
  model: gemini-2.0-flash-thinking-exp-01-21
  baseUrl: https://generativelanguage.googleapis.com/v1beta/

server:
  port: 8080