spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/flixfinder}
    username: flixuser
    password: flixpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

openai:
  apiKey: apiKey
  model: gemini-2.0-flash-thinking-exp-01-21
  baseUrl: https://generativelanguage.googleapis.com/v1beta/

tmdb:
  apiKey: apiKey
  baseUrl: https://api.themoviedb.org/3

server:
  port: 8080